model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "../../shared/data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [2]
  log_save_interval: 100
  min_epochs: 1
  max_epochs: 50
  weights_summary: 'full'

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
